services:

  # Grafana: The open and composable observability and data visualization platform. Visualize metrics, logs, and traces from multiple sources.
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3001:3000" 
    networks:
      - proxy
    volumes:
      - /docker/grafana:/var/lib/grafana
    environment:
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
      - TZ=America/New_York
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=authentik
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=zkUny5iwF2qlJVW7dTQpwy6del5xssX5h6VMckCX
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=FtvjtQYwH04GWMJJWGHJ2KrfvrtjzG9Bz1rax2CMnydgdn8HClQj91hYyfNwTUTeTv1gjndooJyarDOtUYNwMsN6jwqC3Tx4EmukYld0j0dGtvsA0Ezqh4UyacPV8mbS
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://authentik.rjester.us/application/o/authorize/
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://authentik.rjester.us/application/o/token/
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://authentik.rjester.us/application/o/userinfo/
      - GF_AUTH_SIGNOUT_REDIRECT_URL=https://authentik.rjester.us/application/o/grafana/end-session/
      # Optionally enable auto-login (bypasses Grafana login screen)
      #- GF_AUTH_OAUTH_AUTO_LOGIN=true
      ## Optionally map user groups to Grafana roles
      #- "GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
      ## Required if Grafana is running behind a reverse proxy
      #- GF_SERVER_ROOT_URL=https://grafana.rjester.us
    restart: unless-stopped
    labels:
     - homepage.group=Analytics
     - homepage.name=Grafana  
     - homepage.icon=grafana.png
     - homepage.href=https://grafana.rjester.us/
     - homepage.description=Grafana
     - homepage.widget.type=grafana
     - homepage.widget.url=https://grafana.rjester.us
     - homepage.widget.username=admin
     - homepage.widget.password=d0pp3lg4ng3r
     - homepage.widget.version=2
     - traefik.enable=true
     - traefik.http.routers.grafana.rule=Host(`grafana.rjester.us`)
     - traefik.http.routers.grafana.entrypoints=https
     - traefik.http.routers.grafana.tls=true
     - traefik.http.routers.grafana.tls.domains[0].main=rjester.us
     - traefik.http.routers.grafana.tls.domains[0].sans[0]=*.rjester.us
     - traefik.http.routers.grafana.tls.certresolver=cloudflare
     - traefik.http.services.grafana.loadbalancer.server.port=3000
     - traefik.docker.network=proxy
networks:
  proxy:
    external: true
  