---
services:
  infisical:
    image: infisical/infisical:v0.158.0
    restart: unless-stopped
    container_name: infisical
    environment:
      - NODE_ENV=production
      - SITE_URL=${SITE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - DB_CONNECTION_URI=${DB_CONNECTION_URI}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      infisical_postgres:
        condition: service_healthy
      infisical_redis:
        condition: service_started
    networks:
      - infisical_backend
      - proxy
    ports:
      - 8180:8080
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.services.infisical.loadBalancer.server.port=8080
      - traefik.http.routers.infisical_http.service=infisical
      - traefik.http.routers.infisical_http.rule=Host(`infisical.home.arpa`)
      - traefik.http.routers.infisical_http.entrypoints=http
      - traefik.http.routers.infisical_https.service=infisical
      - traefik.http.routers.infisical_https.rule=Host(`infisical.home.arpa`)
      - traefik.http.routers.infisical_https.entrypoints=https
      - traefik.http.routers.infisical_https.tls=true
      - traefik.http.routers.infisical_https.tls.certresolver=cloudflare
  infisical_postgres:
    image: docker.io/library/postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=$${POSTGRES_USER} --dbname=$${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - infisical_backend
    volumes:
      - /docker/infisical/postgres:/var/lib/postgresql/data
  infisical_redis:
    image: docker.io/library/redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - infisical_backend
    volumes:
      - /docker/infisical/redis:/data

networks:
  infisical_backend:
    driver: bridge
  proxy:
    external: true
