
services:
    velxio:
        image: 'ghcr.io/davidmonterocrespo24/velxio:master'
        ports:
            - '3080:80'
            - '3081:8001'
        volumes:
          - /docker/velxio/data:/app/data