http:
  routers:

    # -----------------------
    # Traefik Dashboard
    # -----------------------
    traefik-dashboard:
      entryPoints:
        - https
      rule: "Host(`traefik-dashboard.local.solemnorangutan.com`) || Host(`traefik-dashboard.rjester.us`)"
      middlewares:
        - secured
        - auth
      tls: {}
      service: api@internal

    # -----------------------
    # External Services
    # -----------------------

    portainer:
      entryPoints: [https]
      rule: "Host(`portainer.local.solemnorangutan.com`) || Host(`portainer.local.russjester.com`) || Host(`portainer.rjester.us`)"
      middlewares:
        - secured
      tls: {}
      service: portainer

    adguard-primary:
      entryPoints: [https]
      rule: "Host(`adguard-primary.rjester.us`)"
      #middlewares:
      #  - secured
      tls: {}
      service: adguard-primary

    adguard-secondary:
      entryPoints: [https]
      rule: "Host(`adguard-secondary.rjester.us`)"
      middlewares:
        - secured
      tls: {}
      service: adguard-secondary

    homeassistant:
      entryPoints: [https]
      rule: "Host(`homeassistant.local.solemnorangutan.com`) || Host(`homeassistant.local.russjester.com`) || Host(`homeassistant.rjester.us`)"
      middlewares:
        - secured
      tls: {}
      service: homeassistant

    jellyfin:
      entryPoints: [https]
      rule: "Host(`media.local.solemnorangutan.com`) || Host(`media.local.russjester.com`) || Host(`media.rjester.us`)"
      middlewares:
        - secured
      tls: {}
      service: jellyfin

  services:
    portainer:
      loadBalancer:
        serversTransport: portainer-transport
        servers:
          - url: "https://192.168.0.125:9443"
        passHostHeader: true

    adguard-primary:
      loadBalancer:
        servers:
          - url: "http://192.168.0.74:80"
        passHostHeader: true

    adguard-secondary:
      loadBalancer:
        servers:
          - url: "http://192.168.0.211:80"
        passHostHeader: true

    homeassistant:
      loadBalancer:
        servers:
          - url: "http://192.168.0.230:8123"
        passHostHeader: true

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.0.125:8096"
        passHostHeader: true

