services:
  traefik1:
    image: traefik:v3.6.15
    container_name: traefik1
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    networks:
      - proxy

    ports:
      - "80:80"
      - "443:443"

    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_api_token

    secrets:
      - cf_api_token

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml:ro
      - ./config:/config:ro
      - ./data/acme.json:/acme.json

  traefik-manager:
    image: ghcr.io/chr0nzz/traefik-manager:latest
    container_name: traefik-manager
    restart: unless-stopped

    depends_on:
      - traefik1

    networks:
      - proxy
      - socket-proxy-net

    volumes:
      - ./config/traefik.yml:/app/traefik.yml

    environment:
      COOKIE_SECURE: "true"
      TRAEFIK_API_URL: http://traefik1:8080
      STATIC_CONFIG_PATH: /app/traefik.yml
      RESTART_METHOD: proxy
      TRAEFIK_CONTAINER: traefik1
      DOCKER_HOST: tcp://socket-proxy:2375

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # HTTP router (redirect to HTTPS)
      - "traefik.http.routers.tm.entrypoints=http"
      - "traefik.http.routers.tm.rule=Host(`traefik-manager.rjester.us`)"
      - "traefik.http.routers.tm.middlewares=https-redirectscheme@file"

      # HTTPS router
      - "traefik.http.routers.tm-secure.entrypoints=https"
      - "traefik.http.routers.tm-secure.rule=Host(`traefik-manager.rjester.us`)"
      - "traefik.http.routers.tm-secure.tls=true"
      - "traefik.http.routers.tm-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.tm-secure.service=tm"

      # Service port
      - "traefik.http.services.tm.loadbalancer.server.port=5000"

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      POST: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy-net

secrets:
  cf_api_token:
    file: ./secrets/cf_api_token.txt

networks:
  proxy:
    external: true
  socket-proxy-net:
    internal: true