services:
  traefik1:
    image: traefik:v3.6.15
    container_name: traefik1
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    networks:
      - proxy

    ports:
      - "80:80"
      - "443:443"

    environment:
      #CF_DNS_API_TOKEN_FILE: /run/secrets/cf_api_token
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}

    # secrets:
    #   - cf_api_token

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/traefik/data/traefik.yml:/traefik.yml:ro
      - ./data:/config
      - /docker/traefik/data/acme.json:/acme.json

  traefik-manager:
    image: ghcr.io/chr0nzz/traefik-manager:latest
    container_name: traefik-manager
    restart: unless-stopped

    depends_on:
      - traefik1

    networks:
      - proxy

    environment:
      TRAEFIK_MANAGER_TRAEFIK_URL: http://traefik1:8080

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # HTTP router (redirect to HTTPS)
      - "traefik.http.routers.tm.entrypoints=http"
      - "traefik.http.routers.tm.rule=Host(`traefik-manager.local.solemnorangutan.com`)"
      - "traefik.http.routers.tm.middlewares=https-redirectscheme@file"

      # HTTPS router
      - "traefik.http.routers.tm-secure.entrypoints=https"
      - "traefik.http.routers.tm-secure.rule=Host(`traefik-manager.local.solemnorangutan.com`)"
      - "traefik.http.routers.tm-secure.tls=true"
      - "traefik.http.routers.tm-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.tm-secure.service=tm"

      # Service port
      - "traefik.http.services.tm.loadbalancer.server.port=8080"

# secrets:
#   cf_api_token:
#     file: ./secrets/cf_api_token.txt

networks:
  proxy:
    external: true