---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/rjester
    - Gitlab:
        - abbr: GL
          href: https://gitlab.com/rjester

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
